name: 'Setup Node.js and pnpm'
description: 'Reusable action to setup Node.js and pnpm with caching'

inputs:
  node-version:
    description: 'Node.js version to install'
    required: false
    default: 'lts/*'
  enable-cache:
    description: 'Enable pnpm store caching'
    required: false
    default: 'true'
  frozen-lockfile:
    description: 'Use frozen lockfile for pnpm install'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Setup pnpm
      uses: pnpm/action-setup@v4

    - name: Get pnpm store directory
      if: inputs.enable-cache == 'true'
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - name: Setup pnpm cache
      if: inputs.enable-cache == 'true'
      uses: actions/cache@v4
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      shell: bash
      run: pnpm install${{ inputs.frozen-lockfile == 'true' && ' --frozen-lockfile' || '' }}
      env:
        GITHUB_TOKEN: ${{ github.token }}