name: Copilot Setup Steps

# This workflow defines the setup steps that GitHub Copilot agents will use
# to prepare the development environment for the vibe-dashboard project.
# It preinstalls tools and dependencies needed for Node.js and TypeScript development.

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
    paths:
      - .github/workflows/copilot-setup-steps.yml
  push:
    branches:
      - main
    paths:
      - .github/workflows/copilot-setup-steps.yml

permissions: {}

jobs:
  copilot-setup-steps:
    name: Setup Development Environment for Copilot
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup-node-pnpm
        with:
          enable-cache: false
          frozen-lockfile: false

      - name: Run lint
        run: pnpm lint

      - name: Build project
        run: pnpm build
